name: Echo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Git clone 
        run: echo "git clone"

      - name: Docker build 
        run: echo "docker build"

      - name: Docker push 
        run: echo "docker push"

      - name: Docker pull 
        run: echo "docker pull"

      - name: Docker run 
        run: echo 'docker run'
