name: Flow for ikan automation

on:
  push:
    branches:
      - main

jobs:
  sample-ikan:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: echo"git clone"

      - name: Docker build
        run: echo "docker build"

      - name: Docker push
        run: echo "docker push"

      - name: Docker pull
        run: echo "docker pull"

      - name: Docker run
        run: echo "docker run"
